module.exports = {
    s2c: {
        "status": "status",
        "from": "from",
        "tripType": "tt",
        "to": "to",
        "depDate": "depD",
        "depTime": "depT",
        "arrDate": "arrD",
        "arrTime": "arrT",
        "duration": "dur",
        "userId": "uid",
        "tripId": "tid",
        "pickFlag": "pf",
        "dropAtCarrier":"dpAtCarr",
        "collectFrmCarrier":"ctFrmCarr",
        "pick": "pick",
        "range": "rng",
        "fDate": "fd",
        "tDate": "td",
        "fTime": "ftm",
        "tTime": "ttm",
        "deliverFlag": "df",
        "deliver": "del",
        "carryDocument": "cd",
        "document": "doc",
        "size": "siz",
        "qnty": "qnt",
        "carryPackage": "cp",
        "package": "pkg",
        "weight": "wt",
        "units": "unt",
        "air": "air",
        "depTerminal": "dTem",
        "arrTerminal": "aTem",
        "pnr": "pnr",
        "flightNumber": "fNum",
        "rail": "rail",
        "trainNumber": "tNum",
        "road": "road",
        "createdAt": "cdt",
        "updatedAt": "udt",
        "user": "usr",
        "name": "name",
        "tripNotAvailable": {en: "Trip is not available", ar:"الرحلة غير متاحة "},
        "invalidQRCode": {en: "Invalid QR Code", ar: "كود الإستجابة السريع غير متاح "},
        "pickupCompleted": {en: "Pickup has already been completed", ar: "تم الإنتهاء من عملية الإستلام"},
        "dropCannotBeforePickup": {en: "Drop cannot be before pickup", ar: "لايمكن التسليم قبل استلام الشحنة"},
        "dropCompleted": {en : "Drop has already been completed", ar: "تم الإنتهاء من عملية التسليم"},
        "shipmentStatusUpdated": {en: "Shipment status updated successfully", ar: "تم تحديث حالة الشحنة خاصتك بنجاح "},
        "weightExceeding": {en: "Weight is exceeding the Traveller's limit", ar: "تجاوز الوزن الحد المسموح به للمسافر"},
        "amountIsZero": {en: "No extra amount is required to be paid", ar: "لا يتوجب دفع أي مبالغ إضافية"},
        "cntCancelTripShipmntPicked": { en: "Cannot cancel the trip once shipment has been picked up", ar: "لا يمكن إلغاء الرحلة بمجرد استلام الشحنة"},
        "existsUnpaidInvoice": {en: "Unpaid invoice exists", ar: "يوجد فاتورة غير مدفوعة "},
        "noShipmentToCancel": {en: "There is no shipment to cancel", ar: "لايوجد أي شحنة للإلغاء "},
        "tripNotAvailableToCancel": {en: "Trip is not available to cancel", ar: "الرحلة غير متوفرة حتى يتم إلغاؤها "},
        "trvlDateCntBfreToDay": {en: "Travel date cannot be before the today's date", ar: "تاريخ المغادرة لايمكن ان يكون قبل تاريخ اليوم "},
        "trvltmeCntBfreCurntTme": {en: "Travel time cannot be before current time", ar: "وقت المغادرة لايمكن ان يكون قبل الوقت الحالي "},
        "arrDteCntBfreTodayDte": {en: "Arrival date cannot be before the today's date", ar: "تاريخ الوصول لايمكن ان يكون قبل تاريخ اليوم"},
        "arrTmeCntbfreCurTme": {en: "Arrival time cannot be before current time", ar: "وقت الوصول لايمكن ان يكون قبل الوقت الحالي"},
        "pkgwgtExcTrvlLmt": {en: "Package Weight is exceeding the traveller limit", ar: "وزن الطرد تجاوز الحد المحدد من قبل المسافر "},
        "pkgQtyExcTrvlLmt": {en: "Package quantity is exceeding the traveller limit", ar: "كمية الطرد تجاوزت الحد المحدد من قبل المسافر"},
        "docWgtExcTrvlLmt": {en : "Document Weight is exceeding the traveller limit", ar: "وزن الملف تجاوز الحد المحدد من قبل المسافر"},
        "docQtyExcTrvlLmt": {en: "Document quantity is exceeding the traveller limit", ar: "كمية الملف تجاوزت الحد المحدد من قبل المسافر"},
        "shpDeclinedSuccess": {en: "Shipment request has been declined successfully", ar: "تم رفض طلب الشحن "},
        "ReqOnHold": {en: "Request already on hold", ar: "الطلب معلق بالفعل "},
        "carryNotAvailable": {en: "Carry is not available", ar: "Carry is not available"},
        "shpCancelledSuccess": {en: "Shipment has been cancelled successfully", ar: "Shipment has been cancelled successfully"},



        "errorInProfile": {en: "Error in getting profile information", ar:"Error in getting profile information"},
        "errorInTripCount": {en : "Error in getting active trips count", ar: "Error in getting active trips count"},
        "errorInShipmentsCount": {en : "Error in getting active shipments count", ar: "Error in getting active shipments count"},
        "errorInInvoiceCount": {en: "Error in getting active invoices count", ar: "Error in getting active invoices count"},
        "errorInActiveTrips": {en: "Error in getting active trips", ar: "Error in getting active trips"},
        "errorInCompletedTripsCount": {en: "Error in getting completed trips count", ar: "Error in getting completed trips count"},
        "errorInCompletedTrips": {en: "Error in getting completed trips", ar: "Error in getting completed trips"},
        "errorInTripCityNames": {en: "Error in getting city tripNotAvailableToCancelnames in trips", ar: "Error in getting city names in trips"},
        "errorInTripInfo": {en: "Error in getting trip information", ar: "Error in getting trip information"},
        "errorInReceivedItemsCount": {en: "Error in getting received items count", ar: "Error in getting received items count"},
        "errorInCarryItem": {en: "Error in getting carry items", ar:"Error in getting carry items"},
        "errorInCarryUserName": {en: "Error in getting carry user name", ar: "Error in getting carry user name"},
        "errorInShipmentInformation": {en: "Error in getting shipments information", ar: "Error in getting shipments information"},
        "errorInShipmentsCount": {en: "Error in getting active shipments count", ar: "Error in getting active shipments count"},
        "errorInCityName": {en: "Error in getting city names", ar: "Error in getting city names"},
        "errorInActiveShipments": {en: "Error in getting active shipments", ar: "Error in getting active shipments"},
        "errorInCompletedShipmentsCount": {en: "Error in getting completed shipments count", ar: "Error in getting completed shipments count"},
        "errorInCompletedShipments": {en: "Error in getting active shipments", ar: "Error in getting active shipments"},
        "errorInProductDetails": {en: "Error in getting Product Details", ar: "Error in getting Product Details"},
        "errorInGettingCarryId": {en: "Error in getting carryId", ar: "Error in getting carryId"},
        "errorInTrackingInfo": {en: "Error getting tracking information", ar: "Error getting tracking information"},
        "errorInCancelingTrip": {en: "Error in canceling the trip", ar: "Error in canceling the trip"},
        "errorInCancelingRequests": {en: "Error in canceling the carry item for this trip", ar: "Error in canceling the carry item for this trip"},
        "errInChangeBookingInfoStatus": {en: "Error in changing the booking info status", ar: "Error in changing the booking info status"},
        "errInCancellingShipment": {en: "Error in canceling the shipment", ar: "Error in canceling the shipment"},
        "errIngettingCarryIdNdReason": {en: "Error in getting carry id and reason", ar: "Error in getting carry id and reason"},
        "errIngettingCarryId": {en: "Error in getting carry id", ar: "Error in getting carry id"},
        "errIngettingReason": {en: "Error in getting reason", ar: "Error in getting reason"},
        "errInUpdatingShipmentStatus": {en: "Error in updating shipment status", ar: "Error in updating shipment status"},
        "errInUpdatingPickUpStatus": {en: "Error in updating pickup status", ar: "Error in updating pickup status"},
        "errInUpdatingDropOffStatus": {en : "Error in updating drofOff status", ar: "Error in updating drofOff status"},
        "errInQRCode": {en: "Error in QR Code Verification", ar: "Error in QR Code Verification"},
        "errInPriceQuote": {en: "Error in generating price Quote", ar: "Error in generating price Quote"},
        "errInRequiredFields": {en: "Error in getting required fileds", ar: "Error in getting required fileds"},
        "errCheckingUnpaidInvoice": {en: "Error while checking unpaid invoice", ar: "Error while checking unpaid invoice"},
        "errInGettingCarryWeight": {en: "Error in getting carry weight", ar: "Error in getting carry weight"},
        "errInGettingPaidPrice": {en: "Error in getting paid price", ar: "Error in getting paid price"},
        "errInGettingInvoice": {en: "Error in getting invoice", ar: "Error in getting invoice"},
        "errInGettingCarrierTxn": {en: "Error in getting carrier transaction", ar: "Error in getting carrier transaction"},
        "errInIdProofVali": {en: "Error in ID proof validation", ar: "Error in ID proof validation"},
        "errInSaveIdProof": {en: "Error in save id proofs", ar: "Error in save id proofs"},
        "errInGettingIdProof": {en: "Error in getting id proofs", ar: "Error in getting id proofs"},
        "errInStoreBankInfo": {en: "Error in storing bank information", ar: "Error in storing bank information"},
        "errIngettingBankInfo": {en: "Error in getting bank information", ar: "Error in getting bank information"},
    }
    ,
    c2s: {}
}
